# Generated by Django 5.0.4 on 2024-05-10 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tekoagua', '0003_company_is_active_companytrashowner_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
    ]
